version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_ACCESS_SECRETKEY=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRETKEY=${JWT_REFRESH_SECRET}
      - APP_DEFAULT_ADMIN_USERNAME=${ADMIN_USERNAME}
      - APP_DEFAULT_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - APP_DEFAULT_ADMIN_EMAIL=${ADMIN_EMAIL}

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: